all: forLoopArray memsetArray bracketVsAdd
	echo done

forLoopArray:
	gcc forLoopArray.c -o forLoopArray.exe

memsetArray:
	gcc memsetArray.c -o memsetArray.exe

bracketVsAdd:
	gcc bracketVsAdd.c -o bracketVsAdd.exe
