all: double float int

double:
	gcc doubleToBinaryString.c -o doubleToBinaryString.exe -g

float:
	gcc floatToBinaryString.c -o floatToBinaryString.exe -g

int:
	gcc intToBinaryString.c -o intToBinaryString.exe -g
