doubleToBinaryString.exe 23 >  test.txt
doubleToBinaryString.exe 24 >> test.txt
doubleToBinaryString.exe 25 >> test.txt
doubleToBinaryString.exe 26 >> test.txt
doubleToBinaryString.exe 27 >> test.txt
doubleToBinaryString.exe 28 >> test.txt
doubleToBinaryString.exe 29 >> test.txt
doubleToBinaryString.exe 30 >> test.txt
doubleToBinaryString.exe 31 >> test.txt
doubleToBinaryString.exe 32 >> test.txt
doubleToBinaryString.exe 33 >> test.txt
doubleToBinaryString.exe 34 >> test.txt
doubleToBinaryString.exe 35 >> test.txt
doubleToBinaryString.exe 36 >> test.txt
doubleToBinaryString.exe 37 >> test.txt
doubleToBinaryString.exe 38 >> test.txt
doubleToBinaryString.exe 39 >> test.txt
doubleToBinaryString.exe 40 >> test.txt
doubleToBinaryString.exe 41 >> test.txt
doubleToBinaryString.exe 42 >> test.txt
doubleToBinaryString.exe 43 >> test.txt
doubleToBinaryString.exe 44 >> test.txt
doubleToBinaryString.exe 45 >> test.txt
doubleToBinaryString.exe 46 >> test.txt
doubleToBinaryString.exe 47 >> test.txt
doubleToBinaryString.exe 48 >> test.txt
doubleToBinaryString.exe 49 >> test.txt
doubleToBinaryString.exe 50 >> test.txt
doubleToBinaryString.exe 51 >> test.txt
doubleToBinaryString.exe 52 >> test.txt
doubleToBinaryString.exe 53 >> test.txt
doubleToBinaryString.exe 54 >> test.txt
doubleToBinaryString.exe 55 >> test.txt
doubleToBinaryString.exe 56 >> test.txt
doubleToBinaryString.exe 57 >> test.txt
doubleToBinaryString.exe 58 >> test.txt
doubleToBinaryString.exe 59 >> test.txt
doubleToBinaryString.exe 60 >> test.txt
doubleToBinaryString.exe 61 >> test.txt
doubleToBinaryString.exe 62 >> test.txt
