CC=gcc
INCLUDE=../../Libraries/
LINKS=../../Libraries/lib/
FLAGS=-lSDL2main -lSDL2 -lSDL2_image 
SETUP=-g -lmingw32 -mwindows -mconsole 
all:
	$(CC) main.c -o main $(SETUP) -I$(INCLUDE) -L$(LINKS) $(FLAGS)
